apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-book-details
  labels:
    app: author-book-details
spec:
  replicas: 6
  selector:
    matchLabels:
      app: author-book-details
  template:
    metadata:
      labels:
        app: author-book-details
    spec:
      containers:
        - name: author-book-details
          image: 0481626557.dkr.ecr.eu-west-2.amazonaws.com/author-book-details:latest
          ports:
            - containerPort: 8080
