apiVersion: v1
kind: Service
metadata:
  name: author-book-details
  labels:
    app: author-book-details
spec:
  ports:
      - name: http
        port: 80
        targetPort: 8080
  type: LoadBalancer
  selector:
    app: author-book-details


